import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Minha Página de Links",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-gray-100 text-black min-h-screen flex items-center justify-center p-4">
        {children}
      </body>
    </html>
  );
}
